name: dart_board_firebase_database
description: Firebase Database Binding's
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board

# Configure firebase as per firebase documents
# E.g. configure the runner's with your keys for this to work

version: 1.0.18

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_core: ^0.9.16+5
  dart_board_firebase_core: ^1.4.5
  cloud_firestore: ^2.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.dart_board_authentication_google
    iosBundleIdentifier: com.example.dartBoardAuthenticationGoogle
