// Autogenerated from Pigeon (v1.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name
// @dart = 2.12
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/foundation.dart' show WriteBuffer, ReadBuffer;
import 'package:flutter/services.dart';

class _NavCodec extends StandardMessageCodec {
  const _NavCodec();
}
abstract class Nav {
  static const MessageCodec<Object?> codec = _NavCodec();

  void setNavRoot(String route);
  static void setup(Nav? api) {
    {
      const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.Nav.setNavRoot', codec);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null, 'Argument for dev.flutter.pigeon.Nav.setNavRoot was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_route = args[0] as String?;
          assert(arg_route != null, 'Argument for dev.flutter.pigeon.Nav.setNavRoot was null, expected non-null String.');
          api.setNavRoot(arg_route!);
          return;
        });
      }
    }
  }
}
