name: dart_board_particles
description: A particle system for dart-board.
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board
version: 1.3.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_core: ^0.9.16+5
  dart_board_widgets: ^1.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.dart_board_particles
    iosBundleIdentifier: com.example.dartBoardParticles
