name: dart_board_template_bottomnav
description: A basic template example that works with the Bottom Nav and registered DartBoard routes using RouteView.
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board

version: 0.9.5+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_core: ^0.9.16+5
  dart_board_locator: ^0.9.10
  logging: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: io.dart-board.bottom_nav
    iosBundleIdentifier: io.dart-board.bottom_nav
