name: dart_board_emitter
description: A message bus/emit/receiver for dart board
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board

version: 1.1.6

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_board_core: ^0.9.16+6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.dart_board_emitter
    iosBundleIdentifier: com.example.dartBoardEmitter
