// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAopDwP4dgPBBiBO5pQVhJbiHNJh7uIlIA',
    appId: '1:911356575335:web:19bd8deac9e8569e279ec2',
    messagingSenderId: '911356575335',
    projectId: 'dart-board-59f93',
    authDomain: 'dart-board-59f93.firebaseapp.com',
    storageBucket: 'dart-board-59f93.firebasestorage.app',
    measurementId: 'G-5XP59PKL4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrSpgihPGygLGyp15re1UWauVAL_JHbW4',
    appId: '1:911356575335:android:ad4804076fb49370279ec2',
    messagingSenderId: '911356575335',
    projectId: 'dart-board-59f93',
    storageBucket: 'dart-board-59f93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkcb52O81ezloaXjgSHoIJKZ9Y-peq2OM',
    appId: '1:911356575335:ios:1f058e50cd6024bc279ec2',
    messagingSenderId: '911356575335',
    projectId: 'dart-board-59f93',
    storageBucket: 'dart-board-59f93.firebasestorage.app',
    androidClientId: '911356575335-ig0p3jjnlvdpjh78r3hppivgi50nm8tl.apps.googleusercontent.com',
    iosClientId: '911356575335-ff6m41ka3o612cb7ua9mks3nusvlb232.apps.googleusercontent.com',
    iosBundleId: 'io.dartboard.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkcb52O81ezloaXjgSHoIJKZ9Y-peq2OM',
    appId: '1:911356575335:ios:1f058e50cd6024bc279ec2',
    messagingSenderId: '911356575335',
    projectId: 'dart-board-59f93',
    storageBucket: 'dart-board-59f93.firebasestorage.app',
    androidClientId: '911356575335-ig0p3jjnlvdpjh78r3hppivgi50nm8tl.apps.googleusercontent.com',
    iosClientId: '911356575335-ff6m41ka3o612cb7ua9mks3nusvlb232.apps.googleusercontent.com',
    iosBundleId: 'io.dartboard.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIia_6LQpFRDycaOtqkCixeRytcP8EP9E',
    appId: '1:911356575335:web:d6e1caed480fad11279ec2',
    messagingSenderId: '911356575335',
    projectId: 'dart-board-59f93',
    authDomain: 'dart-board-59f93.firebaseapp.com',
    storageBucket: 'dart-board-59f93.firebasestorage.app',
    measurementId: 'G-T2BBB8TTPD',
  );
}
