name: dart_board_widgets
description: Utility/Architecture Widgets for Dart Board (or other projects)
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board

version: 1.7.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.dart_board_widgets
    iosBundleIdentifier: com.example.dartBoardWidgets
